package com.coderman.video.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * This is the base record class for table: sys_file
 * Generated by MyBatis Generator.
 * @author coderman - MyBatis Generator
 */
@Data
@ApiModel(value="SysFile", description = "sys_file 实体类")
public class SysFile implements Serializable {
    

    @ApiModelProperty(value = "文件ID")
    private Long id;

    @ApiModelProperty(value = "文件Hash（用于秒传）")
    private String fileHash;

    @ApiModelProperty(value = "原始文件名")
    private String fileName;

    @ApiModelProperty(value = "MIME类型")
    private String fileType;

    @ApiModelProperty(value = "文件大小")
    private Long fileSize;

    @ApiModelProperty(value = "文件访问路径")
    private String fileUrl;

    @ApiModelProperty(value = "存储类型（local/oss/minio）")
    private String storageType;

    @ApiModelProperty(value = "状态：1=有效，0=无效（已删除/失效）")
    private Integer status;

    @ApiModelProperty(value = "创建时间")
    private Date createdAt;

    @ApiModelProperty(value = "更新时间")
    private Date updatedAt;
}