package com.coderman.video.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * This is the base record class for table: upload_part
 * Generated by MyBatis Generator.
 * @author coderman - MyBatis Generator
 */
@Data
@ApiModel(value="UploadPart", description = "upload_part 实体类")
public class UploadPart implements Serializable {
    

    @ApiModelProperty(value = "主键ID，自增")
    private Long id;

    @ApiModelProperty(value = "上传任务ID，对应主任务表的upload_id")
    private String uploadId;

    @ApiModelProperty(value = "分片编号（从1开始）")
    private Integer partNumber;

    @ApiModelProperty(value = "分片标识，OSS使用ETag，本地使用fileHash")
    private String tag;

    @ApiModelProperty(value = "记录创建时间")
    private Date createdAt;
}