package com.coderman.video.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * This is the base record class for table: upload_task
 * Generated by MyBatis Generator.
 * @author coderman - MyBatis Generator
 */
@Data
@ApiModel(value="UploadTask", description = "upload_task 实体类")
public class UploadTask implements Serializable {
    

    @ApiModelProperty(value = "主键ID")
    private Long id;

    @ApiModelProperty(value = "上传任务ID，由服务端生成，唯一标识一个上传过程")
    private String uploadId;

    @ApiModelProperty(value = "文件的Hash值，用于秒传判断和断点续传识别")
    private String fileHash;

    @ApiModelProperty(value = "原始文件名")
    private String fileName;

    @ApiModelProperty(value = "文件总大小（字节）")
    private Long fileSize;

    @ApiModelProperty(value = "文件类型，如 video/mp4、application/pdf 等")
    private String fileType;

    @ApiModelProperty(value = "文件路径")
    private String filePath;

    @ApiModelProperty(value = "分片总数")
    private Integer totalParts;

    @ApiModelProperty(value = "当前正在上传的分片编号，用于断点续传指针记录")
    private Integer partIndex;

    @ApiModelProperty(value = "上传状态：0-初始化，1-上传中，2-已上传，3-已合并，4-取消，5-失败")
    private Integer status;

    @ApiModelProperty(value = "创建时间")
    private Date createdAt;

    @ApiModelProperty(value = "最后更新时间")
    private Date updatedAt;

    @ApiModelProperty(value = "用户id")
    private Long userId;
}