package com.coderman.video.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * This is the base record class for table: user
 * Generated by MyBatis Generator.
 * @author coderman - MyBatis Generator
 */
@Data
@ApiModel(value="User", description = "user 实体类")
public class User implements Serializable {
    

    @ApiModelProperty(value = "主键，自增ID")
    private Long id;

    @ApiModelProperty(value = "用户名，唯一")
    private String username;

    @ApiModelProperty(value = "密码（加密后的哈希值）")
    private String password;

    @ApiModelProperty(value = "昵称")
    private String nickname;

    @ApiModelProperty(value = "邮箱，登录和找回密码用")
    private String email;

    @ApiModelProperty(value = "手机号")
    private String phone;

    @ApiModelProperty(value = "头像地址")
    private String avatarUrl;

    @ApiModelProperty(value = "账号是否启用")
    private Integer enabled;

    @ApiModelProperty(value = "最后登录时间")
    private Date lastLoginAt;

    @ApiModelProperty(value = "角色列表，后期可以做关联表，这里简化")
    private String roles;

    @ApiModelProperty(value = "创建时间")
    private Date createdAt;

    @ApiModelProperty(value = "更新时间")
    private Date updatedAt;
}