server:
  port: 8787
spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/video?useUnicode=yes&rewriteBatchedStatements=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: zhangyukang
logging:
  level:
    root: info
    com.coderman.video.mapper: debug
upload:
  strategy: local
  local:
    base-upload-path: F:\\files
    expire-minutes: 60
    domain: http://localhost:8787

