package com.coderman.video.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.coderman.video.model.Category;

/**
 * This is the base Mapper class for table: category
 * Generated by MyBatis Generator.
 * @author 亚声威格 - MyBatis Generator
 */
public interface CategoryMapper extends BaseMapper<Category> {
}