package com.coderman.video.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.coderman.video.model.SysFile;

/**
 * This is the base Mapper class for table: sys_file
 * Generated by MyBatis Generator.
 * @author 亚声威格 - MyBatis Generator
 */
public interface SysFileMapper extends BaseMapper<SysFile> {
}