package com.coderman.video.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.coderman.video.model.UploadPart;

/**
 * This is the base Mapper class for table: upload_part
 * Generated by MyBatis Generator.
 * @author 亚声威格 - MyBatis Generator
 */
public interface UploadPartMapper extends BaseMapper<UploadPart> {
}