package com.coderman.video.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.coderman.video.model.UploadTask;

/**
 * This is the base Mapper class for table: upload_task
 * Generated by MyBatis Generator.
 * @author 亚声威格 - MyBatis Generator
 */
public interface UploadTaskMapper extends BaseMapper<UploadTask> {
}