package com.coderman.video.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.coderman.video.model.User;

/**
 * This is the base Mapper class for table: user
 * Generated by MyBatis Generator.
 * @author 亚声威格 - MyBatis Generator
 */
public interface UserMapper extends BaseMapper<User> {
}