package com.coderman.video.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.coderman.video.model.Video;
import com.coderman.video.request.VideoPageRequest;
import com.coderman.video.vo.VideoVO;

import java.util.List;

/**
 * This is the base Mapper class for table: video
 * Generated by MyBatis Generator.
 * @author 亚声威格 - MyBatis Generator
 */
public interface VideoMapper extends BaseMapper<Video> {

    List<VideoVO> selectVideoPage(VideoPageRequest req);

    Long countVideoPage(VideoPageRequest req);
}
