package com.coderman.video.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.coderman.video.model.VideoCategory;

/**
 * This is the base Mapper class for table: video_category
 * Generated by MyBatis Generator.
 * @author 亚声威格 - MyBatis Generator
 */
public interface VideoCategoryMapper extends BaseMapper<VideoCategory> {
}